import { Product } from '@/lib/types'

export const arProducts: Product[] = [
  {
    id: 'cxr-vol1-ar',
    sku: 'HR-CXR-AR-001',
    language: 'ar',
    slug: 'ana-fahim-cxr',
    title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø£Ø´Ø¹Ø© Ø§Ù„ØµØ¯Ø± (Chest X-Ray) - Ø§Ù„Ø¬Ø²Ø¡ 1',
    subtitle: 'Vol. 1',
    description: 'Ø§Ù„Ø¯Ù„ÙŠÙ„ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠ Ø§Ù„Ø´Ø§Ù…Ù„ Ù„Ø§Ø­ØªØ±Ø§Ù Ø£Ø´Ø¹Ø© Ø§Ù„ØµØ¯Ø±: Ø¯Ù‚Ø© Ø§Ù„ØªÙ…Ø±ÙƒØ²ØŒ Ø·Ø±ÙŠÙ‚Ø© Ø§Ù„Ù‚Ø±Ø§Ø¡Ø© Ø§Ù„Ù…Ù†Ù‡Ø¬ÙŠØ© Ù…Ù† 7 Ø®Ø·ÙˆØ§ØªØŒ ÙˆØ§Ù„Ù„Ø¢Ù„Ø¦ Ø§Ù„ØªØ´Ø®ÙŠØµÙŠØ©.',
    category: 'X-Ray',
    modality: 'Chest X-Ray',
    cover: '/assets/images/ar/cxr-cover.jpg',
    screenshots: ['/images/products/ar/cxr-01.jpg', '/images/products/ar/cxr-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-cxr',
    status: 'PUBLISHED',
    seo: {
      title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø£Ø´Ø¹Ø© Ø§Ù„ØµØ¯Ø± - Ø§Ù„Ø¬Ø²Ø¡ 1 | Hidden Radiology',
      description: 'Ø§Ù„Ø¯Ù„ÙŠÙ„ Ø§Ù„Ø³Ø±ÙŠØ±ÙŠ Ø§Ù„Ø´Ø§Ù…Ù„ Ù„Ø§Ø­ØªØ±Ø§Ù Ø£Ø´Ø¹Ø© Ø§Ù„ØµØ¯Ø± - Ø¯Ù‚Ø© Ø§Ù„ØªÙ…Ø±ÙƒØ² ÙˆØ·Ø±ÙŠÙ‚Ø© Ø§Ù„Ù‚Ø±Ø§Ø¡Ø© Ø§Ù„Ù…Ù†Ù‡Ø¬ÙŠØ©',
      canonical: '/ar/products/ana-fahim-cxr',
      ogImage: '/assets/images/ar/cxr-cover.jpg',
    },
    disclaimer: 'Ù‡Ø°Ø§ Ø§Ù„Ù…Ù†ØªØ¬ Ø±Ù‚Ù…ÙŠ. Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø´Ø­Ù† ÙØ¹Ù„ÙŠ.',
  },
  {
    id: 'ct-vol2-ar',
    sku: 'HR-CT-AR-001',
    language: 'ar',
    slug: 'ana-fahim-ct',
    title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø£Ø³Ø§Ø³ÙŠØ§Øª Ø§Ù„Ø£Ø´Ø¹Ø© Ø§Ù„Ù…Ù‚Ø·Ø¹ÙŠØ© (CT) - Ø§Ù„Ø¬Ø²Ø¡ 2',
    subtitle: 'Vol. 2',
    description: 'Ø¯Ù„ÙŠÙ„ Ø¥ØªÙ‚Ø§Ù† Ù…Ù‚ÙŠØ§Ø³ Ù‡Ø§ÙˆÙ†Ø³ÙÙŠÙ„Ø¯ (HU)ØŒ Ù…Ø¹Ø§Ù…Ù„Ø§Øª Ø§Ù„Ø¹Ø±Ø¶ (Windowing)ØŒ Ø¶Ø¨Ø· Ø§Ù„Ø¬Ø±Ø¹Ø© Ø§Ù„Ø¥Ø´Ø¹Ø§Ø¹ÙŠØ©ØŒ ÙˆØ§Ù„ØªØ¹Ø§Ù…Ù„ Ù…Ø¹ Ø§Ù„Ù‚Ø·Ø¹ ÙˆØ§Ù„ØªØ´ÙˆÙ‡Ø§Øª.',
    category: 'CT',
    modality: 'Computed Tomography',
    cover: '/assets/images/ar/ct-cover.jpg',
    screenshots: ['/images/products/ar/ct-01.jpg', '/images/products/ar/ct-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-ct',
    status: 'PUBLISHED',
    seo: {
      title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø£Ø³Ø§Ø³ÙŠØ§Øª Ø§Ù„Ø£Ø´Ø¹Ø© Ø§Ù„Ù…Ù‚Ø·Ø¹ÙŠØ© - Ø§Ù„Ø¬Ø²Ø¡ 2 | Hidden Radiology',
      description: 'Ø¯Ù„ÙŠÙ„ Ø¥ØªÙ‚Ø§Ù† CT - Ù…Ø¹Ø§Ù…Ù„Ø§Øª Ø§Ù„Ø¹Ø±Ø¶ ÙˆØ¶Ø¨Ø· Ø§Ù„Ø¬Ø±Ø¹Ø© Ø§Ù„Ø¥Ø´Ø¹Ø§Ø¹ÙŠØ© ÙˆØ§Ù„ØªØ¹Ø§Ù…Ù„ Ù…Ø¹ Ø§Ù„Ù‚Ø·Ø¹ ÙˆØ§Ù„ØªØ´ÙˆÙ‡Ø§Øª',
      canonical: '/ar/products/ana-fahim-ct',
      ogImage: '/assets/images/ar/ct-cover.jpg',
    },
    disclaimer: 'Ù‡Ø°Ø§ Ø§Ù„Ù…Ù†ØªØ¬ Ø±Ù‚Ù…ÙŠ. Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø´Ø­Ù† ÙØ¹Ù„ÙŠ.',
  },
  {
    id: 'mri-vol3-ar',
    sku: 'HR-MRI-AR-001',
    language: 'ar',
    slug: 'ana-fahim-mri',
    title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø§Ù„Ø±Ù†ÙŠÙ† Ø§Ù„Ù…ØºÙ†Ø§Ø·ÙŠØ³ÙŠ (MRI) - Ø§Ù„Ø¬Ø²Ø¡ 3',
    subtitle: 'Vol. 3',
    description: '50 Ø¹Ù„Ø§Ù…Ø© Ø®ÙÙŠØ© Ø£Ø³Ø§Ø³ÙŠØ©ØŒ Ø£Ø³Ø§Ø³ÙŠØ§Øª Ù†Ø¨Ø¶Ø§Øª Ø§Ù„ØªØµÙˆÙŠØ±ØŒ ÙˆØ¨Ø±ÙˆØªÙˆÙƒÙˆÙ„Ø§Øª Ø§Ù„Ø³Ù„Ø§Ù…Ø© Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ© ÙÙŠ Ø§Ù„ØªØµÙˆÙŠØ± Ø¨Ø§Ù„Ø±Ù†ÙŠÙ† Ø§Ù„Ù…ØºÙ†Ø§Ø·ÙŠØ³ÙŠ.',
    category: 'MRI',
    modality: 'Magnetic Resonance Imaging',
    cover: '/assets/images/ar/mri-cover.jpg',
    screenshots: ['/images/products/ar/mri-01.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-mri',
    status: 'PUBLISHED',
    seo: {
      title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø§Ù„Ø±Ù†ÙŠÙ† Ø§Ù„Ù…ØºÙ†Ø§Ø·ÙŠØ³ÙŠ - Ø§Ù„Ø¬Ø²Ø¡ 3 | Hidden Radiology',
      description: 'Ø¯Ù„ÙŠÙ„ MRI - 50 Ø¹Ù„Ø§Ù…Ø© Ø®ÙÙŠØ© Ø£Ø³Ø§Ø³ÙŠØ©ØŒ Ø£Ø³Ø§Ø³ÙŠØ§Øª Ù†Ø¨Ø¶Ø§Øª Ø§Ù„ØªØµÙˆÙŠØ± ÙˆØ¨Ø±ÙˆØªÙˆÙƒÙˆÙ„Ø§Øª Ø§Ù„Ø³Ù„Ø§Ù…Ø© Ø§Ù„Ø³Ø±ÙŠØ±ÙŠØ©',
      canonical: '/ar/products/ana-fahim-mri',
      ogImage: '/assets/images/ar/mri-cover.jpg',
    },
    disclaimer: 'Ù‡Ø°Ø§ Ø§Ù„Ù…Ù†ØªØ¬ Ø±Ù‚Ù…ÙŠ. Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø´Ø­Ù† ÙØ¹Ù„ÙŠ.',
  },
  {
    id: 'qs-vol4-ar',
    sku: 'HR-QS-AR-001',
    language: 'ar',
    slug: 'radiology-quality-safety',
    title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø§Ù„Ø¬ÙˆØ¯Ø© ÙˆØ§Ù„Ø³Ù„Ø§Ù…Ø© ÙÙŠ Ø§Ù„Ø£Ø´Ø¹Ø© - Ø§Ù„Ø¬Ø²Ø¡ 4',
    subtitle: 'Vol. 4',
    description: 'Ù…Ø¹Ø§ÙŠÙŠØ± Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø¬ÙˆØ¯Ø© Ø§Ù„Ø´Ø§Ù…Ù„Ø© Ø¯Ø§Ø®Ù„ Ø£Ù‚Ø³Ø§Ù… Ø§Ù„Ø£Ø´Ø¹Ø©ØŒ Ø³ÙŠØ§Ø³Ø§Øª Ø³Ù„Ø§Ù…Ø© Ø§Ù„Ù…Ø±Ø¶Ù‰ØŒ ÙˆØªØ·Ø¨ÙŠÙ‚ Ø§Ù„Ù…Ø¹Ø§ÙŠÙŠØ± Ø§Ù„Ø¯ÙˆÙ„ÙŠØ© Ø¨Ø¯Ù‚Ø©.',
    category: 'Quality & Safety',
    modality: 'General',
    cover: '/assets/images/ar/qs-cover.jpg',
    screenshots: [],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/radiology-quality-safety',
    status: 'PUBLISHED',
    seo: {
      title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø§Ù„Ø¬ÙˆØ¯Ø© ÙˆØ§Ù„Ø³Ù„Ø§Ù…Ø© ÙÙŠ Ø§Ù„Ø£Ø´Ø¹Ø© - Ø§Ù„Ø¬Ø²Ø¡ 4 | Hidden Radiology',
      description: 'Ù…Ø¹Ø§ÙŠÙŠØ± Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø¬ÙˆØ¯Ø© Ø§Ù„Ø´Ø§Ù…Ù„Ø© ÙˆØ³ÙŠØ§Ø³Ø§Øª Ø³Ù„Ø§Ù…Ø© Ø§Ù„Ù…Ø±Ø¶Ù‰ ÙˆØªØ·Ø¨ÙŠÙ‚ Ø§Ù„Ù…Ø¹Ø§ÙŠÙŠØ± Ø§Ù„Ø¯ÙˆÙ„ÙŠØ©',
      canonical: '/ar/products/radiology-quality-safety',
      ogImage: '/assets/images/ar/qs-cover.jpg',
    },
    disclaimer: 'Ù‡Ø°Ø§ Ø§Ù„Ù…Ù†ØªØ¬ Ø±Ù‚Ù…ÙŠ. Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø´Ø­Ù† ÙØ¹Ù„ÙŠ.',
  },
  {
    id: 'rs-vol5-ar',
    sku: 'HR-RS-AR-001',
    language: 'ar',
    slug: 'ana-fahim-radiation-safety',
    title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø§Ù„Ø³Ù„Ø§Ù…Ø© Ø§Ù„Ø¥Ø´Ø¹Ø§Ø¹ÙŠØ© - Ø§Ù„Ø¬Ø²Ø¡ 5',
    subtitle: 'Vol. 5',
    description: 'Ø§Ù„ÙˆÙ‚Ø§ÙŠØ© Ø§Ù„Ø¥Ø´Ø¹Ø§Ø¹ÙŠØ© Ø§Ù„Ù…ØªÙ‚Ø¯Ù…Ø©ØŒ Ù…Ø¨Ø¯Ø£ ALARAØŒ Ù…Ø±Ø§Ù‚Ø¨Ø© Ø§Ù„Ø¬Ø±Ø¹Ø§ØªØŒ ÙˆØ§Ù„Ø§Ù…ØªØ«Ø§Ù„ Ù„Ù„ÙˆØ§Ø¦Ø­ Ø§Ù„ØªÙ†Ø¸ÙŠÙ…ÙŠØ© Ù„Ù…Ø±Ø§ÙƒØ² Ø§Ù„ØªØµÙˆÙŠØ± Ø§Ù„Ø·Ø¨ÙŠ.',
    category: 'Radiation Safety',
    modality: 'General',
    cover: '/assets/images/ar/rs-cover.jpg',
    screenshots: [],
    price: 7.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-radiation-safety',
    status: 'PUBLISHED',
    seo: {
      title: 'Ø£Ù†Ø§ ÙØ§Ù‡Ù… | Ø§Ù„Ø³Ù„Ø§Ù…Ø© Ø§Ù„Ø¥Ø´Ø¹Ø§Ø¹ÙŠØ© - Ø§Ù„Ø¬Ø²Ø¡ 5 | Hidden Radiology',
      description: 'Ø§Ù„ÙˆÙ‚Ø§ÙŠØ© Ø§Ù„Ø¥Ø´Ø¹Ø§Ø¹ÙŠØ© Ø§Ù„Ù…ØªÙ‚Ø¯Ù…Ø© ÙˆÙ…Ø¨Ø¯Ø£ ALARA ÙˆÙ…Ø±Ø§Ù‚Ø¨Ø© Ø§Ù„Ø¬Ø±Ø¹Ø§Øª ÙˆØ§Ù„Ø§Ù…ØªØ«Ø§Ù„ Ù„Ù„ÙˆØ§Ø¦Ø­ Ø§Ù„ØªÙ†Ø¸ÙŠÙ…ÙŠØ©',
      canonical: '/ar/products/ana-fahim-radiation-safety',
      ogImage: '/assets/images/ar/rs-cover.jpg',
    },
    disclaimer: 'Ù‡Ø°Ø§ Ø§Ù„Ù…Ù†ØªØ¬ Ø±Ù‚Ù…ÙŠ. Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø´Ø­Ù† ÙØ¹Ù„ÙŠ.',
  },
]

