import { Product } from '../../lib/types'

export const arProducts: Product[] = [
  {
    id: 'hr-cxr-ar-001',
    sku: 'HR-CXR-AR-001',
    language: 'ar',
    slug: 'ana-fahim-cxr',
    title: 'أنا فاهم | أشعة الصدر Chest X-Ray',
    subtitle: 'Complete Edition v2.0',
    description: 'دليل شامل لفنيي الأشعة يغطي تقنيات التصوير، قراءة الأفلام، واكتشاف الأخطاء الشائعة في أشعة الصدر. يتضمن أمثلة سريرية حقيقية ونصائح من خبرة 30 عاماً.',
    category: 'X-Ray',
    modality: 'Chest X-Ray',
    cover: '/images/ar/products/cxr-cover.jpg',
    screenshots: ['/images/ar/products/cxr-01.jpg', '/images/ar/products/cxr-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-cxr',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | أشعة الصدر Chest X-Ray | Hidden Radiology',
      description: 'دليل شامل لفنيي الأشعة في أشعة الصدر - تقنيات التصوير وقراءة الأفلام',
      canonical: '/ar/products/ana-fahim-cxr',
      ogImage: '/images/ar/products/cxr-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
  {
    id: 'hr-ct-ar-001',
    sku: 'HR-CT-AR-001',
    language: 'ar',
    slug: 'ana-fahim-ct',
    title: 'أنا فاهم | الأشعة المقطعية (CT)',
    subtitle: 'دليلك المبسط قبل دخول غرفة الأشعة',
    description: 'دليل مبسط وعملي يشرح CT من الأساسيات حتى الاحتراف. يتضمن البروتوكولات، التقنيات، وإرشادات السلامة للفنيين الجدد والمتخصصين.',
    category: 'CT',
    modality: 'Computed Tomography',
    cover: '/images/ar/products/ct-cover.jpg',
    screenshots: ['/images/ar/products/ct-01.jpg', '/images/ar/products/ct-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-ct',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | الأشعة المقطعية CT | Hidden Radiology',
      description: 'دليل مبسط وعملي يشرح CT من الأساسيات حتى الاحتراف',
      canonical: '/ar/products/ana-fahim-ct',
      ogImage: '/images/ar/products/ct-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
  {
    id: 'hr-mri-ar-001',
    sku: 'HR-MRI-AR-001',
    language: 'ar',
    slug: 'ana-fahim-mri',
    title: 'أنا فاهم | الرنين المغناطيسي (MRI)',
    subtitle: 'كل ما تحتاج معرفته عن MRI',
    description: 'دليل شامل يشرح التصوير بالرنين المغناطيسي: السلاسل، التباين، السلامة، وقراءة الصور. دليل عملي للفنيين والأطباء.',
    category: 'MRI',
    modality: 'Magnetic Resonance Imaging',
    cover: '/images/ar/products/mri-cover.jpg',
    screenshots: ['/images/ar/products/mri-01.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-mri',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | الرنين المغناطيسي MRI | Hidden Radiology',
      description: 'دليل شامل للتصوير بالرنين المغناطيسي - السلاسل والتباين والسلامة',
      canonical: '/ar/products/ana-fahim-mri',
      ogImage: '/images/ar/products/mri-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
  {
    id: 'hr-qs-ar-001',
    sku: 'HR-QS-AR-001',
    language: 'ar',
    slug: 'radiology-quality-safety',
    title: 'أنا فاهم | الجودة والسلامة في قسم الأشعة',
    subtitle: 'Radiology Quality & Safety',
    description: 'معايير الجودة والسلامة في أقسام الأشعة باللغة العربية. للفنيين والمدراء. يتضمن قوائم مراجعة ونماذج تقييم.',
    category: 'Quality & Safety',
    modality: 'General',
    cover: '/images/ar/products/qs-cover.jpg',
    screenshots: [],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/radiology-quality-safety',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | الجودة والسلامة في الأشعة | Hidden Radiology',
      description: 'معايير الجودة والسلامة في أقسام الأشعة - للفنيين والمدراء',
      canonical: '/ar/products/radiology-quality-safety',
      ogImage: '/images/ar/products/qs-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
  {
    id: 'hr-rs-ar-001',
    sku: 'HR-RS-AR-001',
    language: 'ar',
    slug: 'ana-fahim-radiation-safety',
    title: 'أنا فاهم | السلامة الإشعاعية',
    subtitle: 'Radiation Safety',
    description: 'أساسيات الحماية من الإشعاع، مبادئ ALARA، جرعات المرضى والعاملين، والامتثال للمعايير الدولية.',
    category: 'Radiation Safety',
    modality: 'General',
    cover: '/images/ar/products/rs-cover.jpg',
    screenshots: [],
    price: 7.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-radiation-safety',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | السلامة الإشعاعية | Hidden Radiology',
      description: 'أساسيات الحماية من الإشعاع ومبادئ ALARA - للفنيين والأطباء',
      canonical: '/ar/products/ana-fahim-radiation-safety',
      ogImage: '/images/ar/products/rs-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
]
