import { Product } from '../../lib/types'

export const arProducts: Product[] = [
  {
    id: 'cxr-vol1-ar',
    sku: 'HR-CXR-AR-001',
    language: 'ar',
    slug: 'ana-fahim-cxr',
    title: 'أنا فاهم | أشعة الصدر (Chest X-Ray) - الجزء 1',
    subtitle: 'Vol. 1',
    description: 'الدليل السريري الشامل لاحتراف أشعة الصدر: دقة التمركز، طريقة القراءة المنهجية من 7 خطوات، واللآلئ التشخيصية.',
    category: 'X-Ray',
    modality: 'Chest X-Ray',
    cover: '/images/products/ar/cxr-cover.jpg',
    screenshots: ['/images/products/ar/cxr-01.jpg', '/images/products/ar/cxr-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-cxr',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | أشعة الصدر - الجزء 1 | Hidden Radiology',
      description: 'الدليل السريري الشامل لاحتراف أشعة الصدر - دقة التمركز وطريقة القراءة المنهجية',
      canonical: '/ar/products/ana-fahim-cxr',
      ogImage: '/images/products/ar/cxr-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
  {
    id: 'ct-vol2-ar',
    sku: 'HR-CT-AR-001',
    language: 'ar',
    slug: 'ana-fahim-ct',
    title: 'أنا فاهم | أساسيات الأشعة المقطعية (CT) - الجزء 2',
    subtitle: 'Vol. 2',
    description: 'دليل إتقان مقياس هاونسفيلد (HU)، معاملات العرض (Windowing)، ضبط الجرعة الإشعاعية، والتعامل مع القطع والتشوهات.',
    category: 'CT',
    modality: 'Computed Tomography',
    cover: '/images/products/ar/ct-cover.jpg',
    screenshots: ['/images/products/ar/ct-01.jpg', '/images/products/ar/ct-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-ct',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | أساسيات الأشعة المقطعية - الجزء 2 | Hidden Radiology',
      description: 'دليل إتقان CT - معاملات العرض وضبط الجرعة الإشعاعية والتعامل مع القطع والتشوهات',
      canonical: '/ar/products/ana-fahim-ct',
      ogImage: '/images/products/ar/ct-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
  {
    id: 'mri-vol3-ar',
    sku: 'HR-MRI-AR-001',
    language: 'ar',
    slug: 'ana-fahim-mri',
    title: 'أنا فاهم | الرنين المغناطيسي (MRI) - الجزء 3',
    subtitle: 'Vol. 3',
    description: '50 علامة خفية أساسية، أساسيات نبضات التصوير، وبروتوكولات السلامة السريرية في التصوير بالرنين المغناطيسي.',
    category: 'MRI',
    modality: 'Magnetic Resonance Imaging',
    cover: '/images/products/ar/mri-cover.jpg',
    screenshots: ['/images/products/ar/mri-01.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-mri',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | الرنين المغناطيسي - الجزء 3 | Hidden Radiology',
      description: 'دليل MRI - 50 علامة خفية أساسية، أساسيات نبضات التصوير وبروتوكولات السلامة السريرية',
      canonical: '/ar/products/ana-fahim-mri',
      ogImage: '/images/products/ar/mri-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
  {
    id: 'qs-vol4-ar',
    sku: 'HR-QS-AR-001',
    language: 'ar',
    slug: 'radiology-quality-safety',
    title: 'أنا فاهم | الجودة والسلامة في الأشعة - الجزء 4',
    subtitle: 'Vol. 4',
    description: 'معايير إدارة الجودة الشاملة داخل أقسام الأشعة، سياسات سلامة المرضى، وتطبيق المعايير الدولية بدقة.',
    category: 'Quality & Safety',
    modality: 'General',
    cover: '/images/products/ar/qs-cover.jpg',
    screenshots: [],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/radiology-quality-safety',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | الجودة والسلامة في الأشعة - الجزء 4 | Hidden Radiology',
      description: 'معايير إدارة الجودة الشاملة وسياسات سلامة المرضى وتطبيق المعايير الدولية',
      canonical: '/ar/products/radiology-quality-safety',
      ogImage: '/images/products/ar/qs-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
  {
    id: 'rs-vol5-ar',
    sku: 'HR-RS-AR-001',
    language: 'ar',
    slug: 'ana-fahim-radiation-safety',
    title: 'أنا فاهم | السلامة الإشعاعية - الجزء 5',
    subtitle: 'Vol. 5',
    description: 'الوقاية الإشعاعية المتقدمة، مبدأ ALARA، مراقبة الجرعات، والامتثال للوائح التنظيمية لمراكز التصوير الطبي.',
    category: 'Radiation Safety',
    modality: 'General',
    cover: '/images/products/ar/rs-cover.jpg',
    screenshots: [],
    price: 7.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-radiation-safety',
    status: 'PUBLISHED',
    seo: {
      title: 'أنا فاهم | السلامة الإشعاعية - الجزء 5 | Hidden Radiology',
      description: 'الوقاية الإشعاعية المتقدمة ومبدأ ALARA ومراقبة الجرعات والامتثال للوائح التنظيمية',
      canonical: '/ar/products/ana-fahim-radiation-safety',
      ogImage: '/images/products/ar/rs-cover.jpg',
    },
    disclaimer: 'هذا المنتج رقمي. لا يوجد شحن فعلي.',
  },
]
