import { ClinicalCase } from '../../lib/types'

export const enCases: ClinicalCase[] = [
  {
    id: 'hr-case-en-001',
    language: 'en',
    slug: 'chest-pneumonia',
    title: 'Pneumonia — Clinical Case',
    modality: 'Chest X-Ray',
    region: 'Chest',
    clinicalContext: 'A 45-year-old patient presents with cough and fever for 5 days.',
    indication: 'Evaluation of a lower respiratory tract infection with clinical suspicion of pneumonia.',
    technique: 'Chest radiography with assessment of positioning, inspiration, exposure, lung fields, and pleural spaces.',
    image: '/assets/images/en/cases/xray/Lobaerpneumonie.jpg',
    imageDescription: 'Chest radiograph demonstrating a focal pulmonary air-space opacity.',
    keyFindings: 'There is a focal right lower-lung air-space opacity with air bronchograms within the area of consolidation.',
    interpretation: 'A focal air-space opacity with air bronchograms, in the appropriate clinical setting, is compatible with pneumonia.',
    differentialDiagnosis: 'Other possibilities include consolidation from alternative causes, atelectasis, and other basal pulmonary opacities. Correlation with the clinical presentation is essential.',
    whatToLookFor: 'Start with image quality, then assess both lungs systematically. Localize the opacity, compare both sides, and look for air bronchograms, volume loss, or pleural effusion.',
    commonMistake: 'Focusing only on the opacity without assessing lung volume, costophrenic angles, and associated findings that may suggest atelectasis or pleural disease.',
    safetyQualityNote: 'When appropriate, a PA projection is preferred to AP in an ambulatory patient, with careful attention to positioning, inspiration, and exposure.',
    finalImpression: 'Focal right lower-lung air-space opacity with air bronchograms, compatible with pneumonia in the appropriate clinical context.',
    takeaway: 'Read chest radiographs systematically: assess quality first, then location, pattern, associated signs, and finally correlate with the clinical context.',
    status: 'PUBLISHED',
    seo: {
      title: 'Clinical Case: Pneumonia | Hidden Radiology',
      description: 'A complete educational chest X-ray case focused on pneumonia.',
      canonical: '/en/cases/chest-pneumonia',
    },
  },
  {
    id: 'hr-case-en-002',
    language: 'en',
    slug: 'ct-brain-stroke',
    title: 'Acute Stroke — CT Case',
    modality: 'CT',
    region: 'Brain',
    clinicalContext: 'A 68-year-old patient presents with sudden altered consciousness and left-sided weakness.',
    indication: 'Urgent evaluation of sudden neurological symptoms with clinical suspicion of acute stroke.',
    technique: 'Non-contrast head CT as part of the initial assessment of acute stroke.',
    image: '/assets/images/en/cases/ct/brain-hemorrhage_1_1.jpg',
    imageDescription: 'Brain CT image obtained during evaluation of an acute neurological presentation.',
    keyFindings: 'Systematically assess for intracranial hemorrhage, loss of gray-white matter differentiation, and early arterial hyperdensity.',
    interpretation: 'Early ischemic stroke findings may be subtle; therefore, the absence of hemorrhage does not mean that the CT examination is normal.',
    differentialDiagnosis: 'The differential includes intracranial hemorrhage, acute ischemic stroke, and clinical stroke mimics. Final interpretation requires the complete clinical and imaging context.',
    whatToLookFor: 'First assess for hemorrhage, then evaluate gray-white differentiation, basal ganglia, insular cortex, intracranial arteries, edema, and mass effect.',
    commonMistake: 'Calling the CT normal simply because there is no obvious hemorrhage, while overlooking subtle early ischemic changes.',
    safetyQualityNote: 'Non-contrast head CT is an important first-line examination in acute stroke assessment. Follow the stroke imaging protocol used by the institution.',
    finalImpression: 'Educational acute-stroke case emphasizing rapid systematic assessment for hemorrhage and early ischemic changes.',
    takeaway: 'On acute brain CT, the absence of hemorrhage does not mean a normal study; actively search for subtle early ischemic signs.',
    status: 'PUBLISHED',
    seo: {
      title: 'Clinical Case: Acute Stroke | Hidden Radiology',
      description: 'A complete educational brain CT case focused on acute stroke assessment.',
      canonical: '/en/cases/ct-brain-stroke',
    },
  },
  {
    id: 'brainstem-pontine-lesion-t2',
    language: 'en',
    slug: 'brainstem-pontine-lesion-t2',
    title: 'Hidden Brainstem Lesion - Pontine Focus on T2',
    modality: 'MRI',
    region: 'Brain',
    clinicalContext: '34-year-old female with dizziness and intermittent numbness. MRI brain to exclude demyelination. Educational case of subtle brainstem lesion.',
    indication: 'Evaluation of suspected brainstem lesion.',
    technique: 'MRI Brain T2 Axial with magnification.',
    image: '/assets/images/ar/cases/mri/MRI Brain-T2-Weighted - Axial Views.jpg',
    imageDescription: 'Small hyperintense focus in dorsal pons.',
    keyFindings: 'Small hyperintense focus in dorsal pons on T2, highlighted by arrow on magnified views. No significant mass effect or surrounding edema. Location in brainstem makes it easy to miss without magnification and systematic review.',
    interpretation: 'Small intra-axial lesion in brainstem. In educational context, favors small inflammatory / demyelinating focus, correlation with clinical context needed.',
    differentialDiagnosis: 'Demyelination (MS), brainstem encephalitis, small infarct, low-grade glioma.',
    whatToLookFor: 'Systematically review brainstem on T2 and FLAIR with magnification, look for small asymmetric foci.',
    commonMistake: 'Missing small brainstem lesions due to small size and pulsation artifacts.',
    safetyQualityNote: 'Educational case only.',
    finalImpression: 'Small pontine focus on T2 - lesson in systematic brainstem review.',
    takeaway: 'Always magnify and review brainstem - small lesions there are easily missed but clinically important.',
    status: 'PUBLISHED',
    seo: { title: 'Hidden Brainstem Lesion', description: 'MRI teaching case', canonical: '/en/cases/brainstem-pontine-lesion-t2' }
  },
  {
    id: 'cervicothoracic-cord-lesion-enhancement',
    language: 'en',
    slug: 'cervicothoracic-cord-lesion-enhancement',
    title: 'Cervicothoracic Cord Lesion - Enhancement Reveals the Hidden',
    modality: 'MRI',
    region: 'Spine',
    clinicalContext: '28-year-old male with progressive lower limb weakness, cervicothoracic spine MRI. Educational case on importance of contrast.',
    indication: 'Evaluation of suspected cord lesion.',
    technique: 'MRI Cervicothoracic Spine T2 & T1 Post-Contrast.',
    image: '/assets/images/ar/cases/mri/MRI CervicalThoracic Spine - T2 & T1 Post-Contrast.png',
    imageDescription: 'Intramedullary focus with enhancement.',
    keyFindings: 'T2: hyperintense intramedullary focus in cervicothoracic cord. T1 post-contrast: faint focal enhancement at same site. Enhancement changes differential.',
    interpretation: 'Enhancing intramedullary cord lesion - favors myelitis or demyelination, needs follow-up.',
    differentialDiagnosis: 'Transverse myelitis, MS, ependymoma, cord infarct.',
    whatToLookFor: 'Always compare T2 with post-contrast T1 in cord lesions.',
    commonMistake: 'T2 only without checking enhancement.',
    safetyQualityNote: 'Educational.',
    finalImpression: 'Cord lesion with faint enhancement - importance of contrast in cord lesions.',
    takeaway: 'Enhancement changes differential completely.',
    status: 'PUBLISHED',
    seo: { title: 'Cord Lesion', description: 'MRI case', canonical: '/en/cases/cervicothoracic-cord-lesion-enhancement' }
  },
  {
    id: 'thoracic-intradural-extramedullary-mass',
    language: 'en',
    slug: 'thoracic-intradural-extramedullary-mass',
    title: 'Intradural Extramedullary Mass',
    modality: 'MRI',
    region: 'Spine',
    clinicalContext: 'Spinal mass compressing cord.',
    indication: 'Evaluation of spinal canal mass.',
    technique: 'MRI Thoracic Spine.',
    image: '/assets/images/ar/cases/mri/MRI & CT Thoracic Spine.jpg',
    imageDescription: 'Rounded mass posterior to thoracic cord.',
    keyFindings: 'Rounded mass posterior to cord pushing cord anteriorly. CSF cleft around mass.',
    interpretation: 'Intradural extramedullary mass - compatible with meningioma.',
    differentialDiagnosis: 'Meningioma, schwannoma.',
    whatToLookFor: 'CSF cleft to differentiate intra vs extramedullary.',
    commonMistake: 'Confusing intra vs extramedullary.',
    safetyQualityNote: 'Educational.',
    finalImpression: 'Compressive extramedullary mass - classic meningioma.',
    takeaway: 'CSF cleft is key.',
    status: 'PUBLISHED',
    seo: { title: 'Extramedullary Mass', description: 'MRI case', canonical: '/en/cases/thoracic-intradural-extramedullary-mass' }
  }
]
