import { ClinicalCase } from '@/lib/types'

export const enCases: ClinicalCase[] = [

  {
    id: 'hr-case-en-001',
    language: 'en',
    slug: 'chest-pneumonia',
    title: 'Pneumonia â€” Clinical Case',
    modality: 'X-Ray',
    region: 'Chest',
    clinicalContext: 'A 45-year-old patient presents with cough and fever for 5 days.',
    indication: 'Evaluation of a lower respiratory tract infection with clinical suspicion of pneumonia.',
    technique: 'Chest radiography with assessment of positioning, inspiration, exposure, lung fields, and pleural spaces.',
    image: '/cases/xray/chest-pneumonia.jpg',
    supportingImage: '/cases/illustrations/safety/x_ray_1.jpg',
    supportingImageDescription: 'Educational illustration about chest X-ray quality and safety.',
    imageDescription: 'Chest radiograph demonstrating a focal pulmonary air-space opacity.',
    keyFindings: 'There is a focal right lower-lung air-space opacity with air bronchograms within the area of consolidation.',
    interpretation: 'A focal air-space opacity with air bronchograms, in the appropriate clinical setting, is compatible with pneumonia.',
    differentialDiagnosis: 'Other possibilities include consolidation from alternative causes, atelectasis, and other basal pulmonary opacities. Correlation with the clinical presentation is essential.',
    whatToLookFor: 'Start with image quality, then assess both lungs systematically. Localize the opacity, compare both sides, and look for air bronchograms, volume loss, or pleural effusion.',
    commonMistake: 'Focusing only on the opacity without assessing lung volume, costophrenic angles, and associated findings that may suggest atelectasis or pleural disease.',
    safetyQualityNote: 'When appropriate, a PA projection is preferred to AP in an ambulatory patient, with careful attention to positioning, inspiration, and exposure.',
    finalImpression: 'Focal right lower-lung air-space opacity with air bronchograms, compatible with pneumonia in the appropriate clinical context.',
    takeaway: 'Read chest radiographs systematically: assess quality first, then location, pattern, associated signs, and finally correlate with the clinical context.',
    status: 'PUBLISHED',
    seo: {
      title: 'Clinical Case: Pneumonia | Hidden Radiology',
      description: 'A complete educational chest X-ray case focused on pneumonia.',
      canonical: '/en/cases/chest-pneumonia',
    },
  },

    {
    id: 'ct-saddle-pulmonary-embolism',
    language: 'en',
    slug: 'ct-saddle-pulmonary-embolism',
    title: 'Massive Pulmonary Embolism — Saddle Embolus',
    modality: 'CT',
    region: 'Chest',
    clinicalContext: 'An emergency presentation with strong clinical suspicion of acute pulmonary embolism.',
    indication: 'Urgent evaluation for pulmonary embolism using CT pulmonary angiography.',
    technique: 'CT pulmonary angiography after intravenous contrast administration.',
    image: '/cases/ct/ct_chest_saddle_embolus.jpg',
    imageDescription: 'A low-attenuation filling defect at the main pulmonary artery bifurcation extending into the right and left pulmonary arteries.',
    supportingImage: '/cases/illustrations/safety/ct_quality_safety_infographic.jpg',
    supportingImageDescription: 'Educational information on CT dose optimization and low-dose protocols.',
    keyFindings: 'A saddle embolus obstructs the main pulmonary artery bifurcation with extension into the right and left pulmonary arteries.',
    interpretation: 'The appearance is consistent with extensive central pulmonary embolism, a potentially life-threatening emergency requiring urgent diagnosis and management.',
    differentialDiagnosis: 'Other causes of intravascular filling defects should be considered and interpreted within the clinical context and CT angiography protocol.',
    whatToLookFor: 'Start with the main pulmonary artery, then assess its bifurcation and the right and left main pulmonary arteries for filling defects.',
    commonMistake: 'Focusing on peripheral branches while overlooking the main pulmonary artery bifurcation.',
    safetyQualityNote: 'Use an appropriate CT pulmonary angiography protocol while balancing image quality, radiation dose, and intravenous contrast.',
    finalImpression: 'Extensive central pulmonary embolism with a saddle embolus at the main pulmonary artery bifurcation.',
    takeaway: 'In CT pulmonary angiography, always assess the main pulmonary artery and its bifurcation before moving to the peripheral branches.',
    status: 'PUBLISHED',
    seo: {
      title: 'CT Case: Saddle Pulmonary Embolus | Hidden Radiology',
      description: 'An educational CT pulmonary angiography case demonstrating extensive central pulmonary embolism.',
      canonical: '/en/cases/ct-saddle-pulmonary-embolism',
    },
  },

  {
    id: 'ct-acute-subdural-hematoma-midline-shift',
    language: 'en',
    slug: 'ct-acute-subdural-hematoma-midline-shift',
    title: 'Acute Subdural Hematoma — 8.0 mm Midline Shift',
    modality: 'CT',
    region: 'Brain',
    clinicalContext: 'An acute neurological presentation with an extra-axial hematoma and mass effect on the brain.',
    indication: 'Urgent evaluation of intracranial hemorrhage and mass effect.',
    technique: 'Non-contrast head CT.',
    image: '/cases/ct/ct_brain_axial_sdh.jpg',
    imageDescription: 'A hyperdense crescentic subdural collection measuring 12.3 mm along the right cerebral convexity with 8 mm midline shift.',
    supportingImage: '/cases/illustrations/safety/ct_brain_safety_best_practices.jpg',
    supportingImageDescription: 'Educational information on CT brain protocols, image quality, and dose optimization.',
    keyFindings: 'A hyperdense subdural collection measuring 12.3 mm with 8 mm midline shift and compression of the lateral ventricle.',
    interpretation: 'The appearance is consistent with acute subdural hematoma with significant mass effect and midline shift, requiring urgent neurosurgical assessment.',
    differentialDiagnosis: 'Other extra-axial collections should be considered based on the imaging appearance and clinical context.',
    whatToLookFor: 'Identify the collection and measure its thickness, then assess midline shift, ventricular compression, and overall mass effect.',
    commonMistake: 'Describing the hemorrhage without measuring or assessing its mass effect and midline shift.',
    safetyQualityNote: 'In acute head injury and intracranial hemorrhage, follow the institutional CT protocol while rapidly assessing critical findings.',
    finalImpression: 'Acute subdural hematoma measuring 12.3 mm with 8.0 mm midline shift and significant mass effect.',
    takeaway: 'Measuring midline shift and assessing mass effect are important when evaluating intracranial hemorrhage severity and urgency.',
    status: 'PUBLISHED',
    seo: {
      title: 'CT Case: Acute Subdural Hematoma | Hidden Radiology',
      description: 'An educational CT case demonstrating acute subdural hematoma with mass effect and midline shift.',
      canonical: '/en/cases/ct-acute-subdural-hematoma-midline-shift',
    },
  },

  {
    id: 'ct-aortic-dissection-type-b',
    language: 'en',
    slug: 'ct-aortic-dissection-type-b',
    title: 'Type B Aortic Dissection — Intimal Flap with True and False Lumen',
    modality: 'CT',
    region: 'Aorta and Chest',
    clinicalContext: 'An acute vascular presentation requiring detailed CT assessment of the aorta.',
    indication: 'Evaluation of suspected aortic dissection.',
    technique: 'CT angiography of the aorta after intravenous contrast administration.',
    image: '/cases/ct/image_3.jpg',
    imageDescription: 'An intimal flap separating the true lumen from the false lumen in the descending aorta.',
    supportingImage: '/cases/illustrations/safety/ct_triphasic_infographic_poster.jpg',
    supportingImageDescription: 'Educational information on CT protocol optimization and image quality.',
    keyFindings: 'An intimal flap separates the true lumen from the false lumen in the descending aorta.',
    interpretation: 'The appearance is consistent with Type B aortic dissection involving the descending aorta.',
    differentialDiagnosis: 'Acute aortic ulcer and intramural hematoma should also be considered among acute aortic syndromes.',
    whatToLookFor: 'Identify the intimal flap, distinguish the true and false lumens, and assess the longitudinal extent of the dissection.',
    commonMistake: 'Failing to follow the intimal flap across sequential images or incorrectly identifying the true and false lumens.',
    safetyQualityNote: 'Aortic CT angiography requires an appropriate protocol and accurate contrast timing for reliable vascular assessment.',
    finalImpression: 'Type B aortic dissection with an intimal flap separating the true and false lumens in the descending aorta.',
    takeaway: 'Recognizing the intimal flap and correctly identifying the true and false lumens are fundamental to diagnosing aortic dissection on CT angiography.',
    status: 'PUBLISHED',
    seo: {
      title: 'CT Case: Type B Aortic Dissection | Hidden Radiology',
      description: 'An educational CT case demonstrating Type B aortic dissection with an intimal flap and true and false lumens.',
      canonical: '/en/cases/ct-aortic-dissection-type-b',
    },
  },

  {
    id: 'brainstem-pontine-lesion-t2',
    language: 'en',
    slug: 'brainstem-pontine-lesion-t2',
    title: 'Hidden Brainstem Lesion - Pontine Focus on T2',
    modality: 'MRI',
    region: 'Brain',
    clinicalContext: '34-year-old female with dizziness and intermittent numbness. MRI brain to exclude demyelination. Educational case of subtle brainstem lesion.',
    indication: 'Evaluation of suspected brainstem lesion.',
    technique: 'MRI Brain T2 Axial with magnification.',
    image: '/cases/mri/brain-t2.jpg',
    supportingImage: '/cases/illustrations/safety/mri_safety_infographic.jpg',
    supportingImageDescription: 'Educational illustration about MRI safety screening and protocol.',
    imageDescription: 'Small hyperintense focus in dorsal pons.',
    keyFindings: 'Small hyperintense focus in dorsal pons on T2, highlighted by arrow on magnified views. No significant mass effect or surrounding edema. Location in brainstem makes it easy to miss without magnification and systematic review.',
    interpretation: 'Small intra-axial lesion in brainstem. In educational context, favors small inflammatory / demyelinating focus, correlation with clinical context needed.',
    differentialDiagnosis: 'Demyelination (MS), brainstem encephalitis, small infarct, low-grade glioma.',
    whatToLookFor: 'Systematically review brainstem on T2 and FLAIR with magnification, look for small asymmetric foci.',
    commonMistake: 'Missing small brainstem lesions due to small size and pulsation artifacts.',
    safetyQualityNote: 'Educational case only.',
    finalImpression: 'Small pontine focus on T2 - lesson in systematic brainstem review.',
    takeaway: 'Always magnify and review brainstem - small lesions there are easily missed but clinically important.',
    status: 'PUBLISHED',
    seo: {
      title: 'Hidden Brainstem Lesion',
      description: 'MRI teaching case',
      canonical: '/en/cases/brainstem-pontine-lesion-t2',
    },
  },

  {
    id: 'cervicothoracic-cord-lesion-enhancement',
    language: 'en',
    slug: 'cervicothoracic-cord-lesion-enhancement',
    title: 'Cervicothoracic Cord Lesion - Enhancement Reveals the Hidden',
    modality: 'MRI',
    region: 'Spine',
    clinicalContext: '28-year-old male with progressive lower limb weakness, cervicothoracic spine MRI. Educational case on importance of contrast.',
    indication: 'Evaluation of suspected cord lesion.',
    technique: 'MRI Cervicothoracic Spine T2 & T1 Post-Contrast.',
    image: '/cases/mri/cervicothoracic-spine.png',
    supportingImage: '/cases/illustrations/safety/braces-mri-artifact.jpg',
    supportingImageDescription: 'Educational illustration about MRI safety screening and protocol.',
    imageDescription: 'Intramedullary focus with enhancement.',
    keyFindings: 'T2: hyperintense intramedullary focus in cervicothoracic cord. T1 post-contrast: faint focal enhancement at same site. Enhancement changes differential.',
    interpretation: 'Enhancing intramedullary cord lesion - favors myelitis or demyelination, needs follow-up.',
    differentialDiagnosis: 'Transverse myelitis, MS, ependymoma, cord infarct.',
    whatToLookFor: 'Always compare T2 with post-contrast T1 in cord lesions.',
    commonMistake: 'T2 only without checking enhancement.',
    safetyQualityNote: 'Educational.',
    finalImpression: 'Cord lesion with faint enhancement - importance of contrast in cord lesions.',
    takeaway: 'Enhancement changes differential completely.',
    status: 'PUBLISHED',
    seo: {
      title: 'Cord Lesion',
      description: 'MRI case',
      canonical: '/en/cases/cervicothoracic-cord-lesion-enhancement',
    },
  },

  {
    id: 'thoracic-intradural-extramedullary-mass',
    language: 'en',
    slug: 'thoracic-intradural-extramedullary-mass',
    title: 'Intradural Extramedullary Mass',
    modality: 'MRI',
    region: 'Spine',
    clinicalContext: 'Spinal mass compressing cord.',
    indication: 'Evaluation of spinal canal mass.',
    technique: 'MRI Thoracic Spine.',
    image: '/cases/mri/thoracic-spine.jpg',
    supportingImage: '/cases/illustrations/safety/mri_safety_screening_educational_poster.jpg',
    supportingImageDescription: 'Educational illustration about MRI safety screening and protocol.',
    imageDescription: 'Rounded mass posterior to thoracic cord.',
    keyFindings: 'Rounded mass posterior to cord pushing cord anteriorly. CSF cleft around mass.',
    interpretation: 'Intradural extramedullary mass - compatible with meningioma.',
    differentialDiagnosis: 'Meningioma, schwannoma.',
    whatToLookFor: 'CSF cleft to differentiate intra vs extramedullary.',
    commonMistake: 'Confusing intra vs extramedullary.',
    safetyQualityNote: 'Educational.',
    finalImpression: 'Compressive extramedullary mass - classic meningioma.',
    takeaway: 'CSF cleft is key.',
    status: 'PUBLISHED',
    seo: {
      title: 'Extramedullary Mass',
      description: 'MRI case',
      canonical: '/en/cases/thoracic-intradural-extramedullary-mass',
    },
  },

  {
    id: 'chest-pneumothorax-ap-supine',
    language: 'en',
    slug: 'chest-pneumothorax-ap-supine',
    title: 'Pneumothorax in the Supine Patient â€” Chest X-Ray',
    modality: 'X-Ray',
    region: 'Chest',
    clinicalContext: 'Educational case of a patient imaged in the AP supine position, with findings that require a systematic search for pneumothorax.',
    indication: 'Chest evaluation in a patient unable to stand, with clinical suspicion of pneumothorax.',
    technique: 'AP chest radiograph obtained in the supine position, with attention to signs that may appear differently from an upright chest radiograph.',
    image: '/cases/xray/Chest-X-ray AP-Supine.jpg',
    supportingImage: '/cases/illustrations/safety/mother_child_xray.webp',
    supportingImageDescription: 'Educational illustration about chest X-ray quality and safety.',
    imageDescription: 'AP supine chest radiograph used as an educational case demonstrating pneumothorax.',
    keyFindings: 'Pleural air is suggested by increased lucency along the basal and lateral portion of the hemithorax. In a supine patient, particular attention should be paid to the Deep Sulcus Sign.',
    interpretation: 'The radiographic findings are consistent with pneumothorax, emphasizing the importance of recognizing supine-specific radiographic signs.',
    differentialDiagnosis: 'Consider other causes of focal increased lucency as well as technical factors that may alter apparent lung transparency.',
    whatToLookFor: 'On a supine AP chest radiograph, do not rely only on the classic pleural line. Inspect the costophrenic angles and basal and lateral chest for the Deep Sulcus Sign.',
    commonMistake: 'Searching for pneumothorax exactly as it is assessed on an upright chest radiograph, which can lead to missed anterior or basal pneumothorax.',
    safetyQualityNote: 'For patients unable to stand, a supine AP radiograph may be necessary. Avoid unnecessary repeat exposure while ensuring adequate positioning and image quality.',
    finalImpression: 'Educational case of pneumothorax on a supine AP chest radiograph, emphasizing the Deep Sulcus Sign and systematic image review.',
    takeaway: 'On a supine chest radiograph, pneumothorax may not appear in the classic way. Always inspect the basal and lateral regions, especially for the Deep Sulcus Sign.',
    status: 'PUBLISHED',
    seo: {
      title: 'Pneumothorax in the Supine Patient | Hidden Radiology',
      description: 'Educational chest X-ray case explaining how to recognize pneumothorax in a supine patient.',
      canonical: '/en/cases/chest-pneumothorax-ap-supine',
    },
  },

  {
    id: 'chest-ap-erect-mobile-icu-resus',
    language: 'en',
    slug: 'chest-ap-erect-mobile-icu-resus',
    title: 'Mobile AP Chest X-Ray â€” ICU / Resuscitation',
    modality: 'X-Ray',
    region: 'Chest',
    clinicalContext: 'Educational case of a critically ill patient requiring mobile chest radiography in an ICU or resuscitation setting.',
    indication: 'Evaluation of the chest in a critically ill patient who requires portable imaging in the ICU or resuscitation environment.',
    technique: 'Mobile AP chest radiograph with assessment of patient positioning, image quality, exposure, rotation, coverage, and the position of visible medical devices and tubes.',
    image: '/cases/xray/Chest-X-ray AP-Erect-Mobile-ICU-Resus.jpg',
    supportingImage: '/cases/illustrations/safety/portable_xray_icu_safety.jpg',
    supportingImageDescription: 'Educational illustration about chest X-ray quality and safety.',
    imageDescription: 'Mobile AP chest radiograph obtained in a critical-care setting for systematic assessment of image quality and medical devices.',
    keyFindings: 'Begin by assessing image quality and coverage, then systematically review the lungs, pleural spaces, heart, mediastinum, and the position of tubes and lines when present.',
    interpretation: 'This educational case focuses on systematic interpretation of a mobile AP chest radiograph in a critical-care setting while recognizing the technical limitations of portable imaging.',
    differentialDiagnosis: 'Any pulmonary abnormality should be interpreted in the clinical context, with attention to distinguishing true disease from changes related to technique, positioning, or projection.',
    whatToLookFor: 'Review image quality first, then assess the lung fields, costophrenic angles, cardiac silhouette, mediastinum, and the position of tubes and lines when present.',
    commonMistake: 'Interpreting pulmonary opacities or apparent cardiac enlargement without considering that a mobile AP projection and patient positioning can alter the radiographic appearance.',
    safetyQualityNote: 'Mobile imaging in critical care requires balancing clinical need with image quality, minimizing unnecessary repeat exposure, and maintaining patient and staff safety.',
    finalImpression: 'Educational case for systematic assessment of a mobile AP chest radiograph in an ICU or resuscitation setting, with emphasis on image quality and safe interpretation.',
    takeaway: 'For mobile chest radiography, assess image quality, technique, and positioning before interpreting any potential abnormality.',
    status: 'PUBLISHED',
    seo: {
      title: 'Mobile AP Chest X-Ray in ICU | Hidden Radiology',
      description: 'Educational mobile chest X-ray case focused on image quality, safety, and systematic interpretation in critical care.',
      canonical: '/en/cases/chest-ap-erect-mobile-icu-resus',
    },
  },

  {
    id: 'mammography-bilateral-standard-views',
    language: 'en',
    slug: 'mammography-bilateral-standard-views',
    title: 'Bilateral Mammography â€” Standard CC and MLO Views',
    modality: 'Mammography',
    region: 'Breast',
    clinicalContext: 'An educational case focused on reviewing standard mammographic views of both breasts, with emphasis on image quality, positioning, and adequate coverage.',
    indication: 'Evaluation of both breasts using standard mammographic views, with review of image quality before proceeding to interpretive assessment.',
    technique: 'Bilateral mammography using standard CC and MLO views, with assessment of positioning, breast coverage, compression, exposure, and symmetry between the two sides.',
    image: '/cases/mammography/mammography-bilateral-standard-views.jpg',
    imageDescription: 'Bilateral mammographic image used to assess standard views, image quality, and adequate breast coverage.',
    supportingImage: '/cases/illustrations/safety/mammography_cc_view_education.jpg',
    supportingImageDescription: 'Educational image demonstrating breast positioning for the CC view, with emphasis on image quality and safety.',
    keyFindings: 'Begin by assessing image quality, positioning, and coverage. Then review the glandular tissue, soft tissues, skin, margins, and symmetry between the two breasts.',
    interpretation: 'This case focuses on a systematic approach to mammographic interpretation and confirming that the views and image quality are adequate before assessing for pathologic findings.',
    differentialDiagnosis: 'Any asymmetry or unusual density should be assessed in the context of positioning and image quality, with comparison to previous examinations when available.',
    whatToLookFor: 'First review breast coverage, positioning, and exposure quality. Then assess the glandular tissue for asymmetry, masses, calcifications, and skin or nipple changes.',
    commonMistake: 'Beginning to interpret suspected abnormalities before confirming that the images are of adequate diagnostic quality and that positioning and coverage are sufficient.',
    safetyQualityNote: 'Mammographic quality depends heavily on appropriate positioning, compression, and adequate breast coverage. Good diagnostic quality should be achieved while maintaining radiation exposure as low as reasonably achievable and avoiding unnecessary repeat imaging.',
    finalImpression: 'An educational case reviewing standard mammographic views, with emphasis on positioning, coverage, and image quality before diagnostic interpretation.',
    takeaway: 'In mammography, appropriate positioning, coverage, and image quality are the first steps before searching for pathologic findings.',
    status: 'PUBLISHED',
    seo: {
      title: 'Bilateral Mammography and Standard Views | Hidden Radiology',
      description: 'An educational mammography case focusing on standard views, image quality, positioning, and safety.',
      canonical: '/en/cases/mammography-bilateral-standard-views',
    },
  },
  {
    id: 'mammography-suspicious-mass-mlo',
    language: 'en',
    slug: 'mammography-suspicious-mass-mlo',
    title: 'Suspicious Mass on Mammography â€” MLO View',
    modality: 'Mammography',
    region: 'Breast',
    clinicalContext: 'An educational case designed to train the eye to identify a suspicious mass on an MLO mammographic view and approach it systematically.',
    indication: 'Evaluation of a focal breast abnormality or mass and assessment of its mammographic characteristics and location.',
    technique: 'Mammography using an MLO view, with assessment of image quality and coverage followed by systematic review of the breast tissue for a mass, asymmetry, or architectural distortion.',
    image: '/cases/mammography/mammography-suspicious-mass-mlo.jpg',
    imageDescription: 'MLO mammographic image demonstrating an educational example of a suspicious mass within the breast tissue.',
    supportingImage: '/cases/illustrations/safety/mammography_mlo_anatomy_diagram.jpg',
    supportingImageDescription: 'Educational anatomical diagram illustrating the relationship between the MLO view and breast anatomy during image assessment.',
    keyFindings: 'A focal area within the breast tissue warrants attention. Its shape, margins, density, and location should be assessed carefully.',
    interpretation: 'Identification of a mass is only the beginning. Its mammographic characteristics should be evaluated and correlated with other views, clinical findings, and additional imaging when indicated.',
    differentialDiagnosis: 'A mass may represent a benign or malignant process or overlapping breast tissue. Its nature cannot be determined from a single imaging feature alone.',
    whatToLookFor: 'Look for masses, asymmetry, architectural distortion, and calcifications. Then assess the shape, margins, density, and location of any identified mass.',
    commonMistake: 'Focusing only on the presence of a mass without analyzing its margins, shape, density, or comparison with other views.',
    safetyQualityNote: 'Diagnostic-quality images should be obtained while avoiding unnecessary repeat examinations. When a suspicious finding is identified, further assessment should follow the appropriate clinical imaging protocol.',
    finalImpression: 'An educational case demonstrating a suspicious mass on the MLO view, emphasizing detection, systematic description, and avoiding a diagnosis based on a single imaging feature.',
    takeaway: 'Finding a mass is only the beginning; describing its shape, margins, density, and comparing it with other views makes the assessment more accurate.',
    status: 'PUBLISHED',
    seo: {
      title: 'Suspicious Mass on MLO Mammography | Hidden Radiology',
      description: 'An educational case for evaluating a suspicious mass on an MLO mammographic view, with emphasis on systematic assessment and image quality.',
      canonical: '/en/cases/mammography-suspicious-mass-mlo',
    },
  },
  {
    id: 'mammography-3d-tomosynthesis',
    language: 'en',
    slug: 'mammography-3d-tomosynthesis',
    title: 'Digital Breast Tomosynthesis â€” 3D Mammography',
    modality: 'Mammography',
    region: 'Breast',
    clinicalContext: 'An educational case introducing digital breast tomosynthesis and demonstrating how breast tissue can be evaluated across sequential reconstructed slices.',
    indication: 'Evaluation of breast tissue and reduction of the effect of tissue overlap when additional information is needed beyond conventional two-dimensional mammography.',
    technique: 'Digital Breast Tomosynthesis with acquisition of a series of thin reconstructed slices, allowing breast tissue to be reviewed layer by layer.',
    image: '/cases/mammography/mammography-3d-tomosynthesis.jpg',
    imageDescription: 'Educational digital breast tomosynthesis image demonstrating assessment of breast tissue across sequential reconstructed slices.',
    supportingImage: '/cases/illustrations/safety/mammography_cc_breast_anatomy.jpg',
    supportingImageDescription: 'Educational breast anatomy image helping illustrate tissue distribution and its relationship to the CC view.',
    keyFindings: 'Tomosynthesis allows breast tissue to be reviewed at multiple levels and reduces the effect of overlapping tissue that may obscure findings on two-dimensional images.',
    interpretation: 'Images should be reviewed systematically across sequential slices, with attention to masses, architectural distortion, asymmetry, and calcifications when present.',
    differentialDiagnosis: 'Some appearances may result from tissue overlap or positioning differences. A finding should therefore be assessed across multiple slices and appropriate views before being considered a true abnormality.',
    whatToLookFor: 'Review sequential slices for a mass, architectural distortion, or asymmetry, and follow any finding across more than one level.',
    commonMistake: 'Making a judgment from a single image or slice without following the finding across sequential slices or considering the effect of tissue overlap.',
    safetyQualityNote: 'The technique should be used according to the appropriate clinical indication and equipment protocol, while maintaining adequate diagnostic quality and avoiding unnecessary examinations or repeat imaging.',
    finalImpression: 'An educational digital breast tomosynthesis case focusing on layer-by-layer assessment of breast tissue and reduction of tissue-overlap effects.',
    takeaway: 'The key advantage of tomosynthesis is the ability to evaluate breast tissue across multiple levels rather than relying only on a two-dimensional image.',
    status: 'PUBLISHED',
    seo: {
      title: 'Digital Breast Tomosynthesis | Hidden Radiology',
      description: 'An educational case on digital breast tomosynthesis and layer-by-layer assessment of breast tissue.',
      canonical: '/en/cases/mammography-3d-tomosynthesis',
    },
  },
  {
    id: 'c-arm-intraoperative-cholangiogram',
    language: 'en',
    slug: 'c-arm-intraoperative-cholangiogram',
    title: 'Intraoperative Cholangiography Using C-Arm',
    modality: 'C-Arm',
    region: 'Biliary Tract',
    clinicalContext: 'An educational case demonstrating the use of a C-Arm during surgery to perform contrast-enhanced imaging of the biliary tract and assess ductal anatomy and contrast passage.',
    indication: 'Evaluation of the biliary tract during surgery, including assessment for obstruction, stones, or other findings requiring further evaluation.',
    technique: 'Use of a C-Arm with injection of contrast material into the biliary ducts, obtaining appropriate fluoroscopic images while optimizing the field of view and minimizing unnecessary radiation exposure.',
    image: '/cases/c-arm/intraoperative_cholangiogram_fluoroscopy.jpg',
    imageDescription: 'Educational fluoroscopic image demonstrating contrast-enhanced imaging of the biliary tract during surgery using a C-Arm.',
    supportingImage: '/cases/illustrations/safety/c_arm_fluoroscopy_cholangiogram.jpg',
    supportingImageDescription: 'Educational image highlighting quality and safety considerations during C-Arm cholangiography, with emphasis on minimizing fluoroscopy time and unnecessary radiation exposure.',
    keyFindings: 'Assess ductal opacification and continuity, the course of the biliary ducts, and contrast passage, while looking for any unexpected filling defect, interruption, or delayed passage.',
    interpretation: 'Images should be reviewed systematically within the surgical context, assessing ductal anatomy and contrast passage rather than relying on a single image when the information is incomplete.',
    differentialDiagnosis: 'Apparent non-opacification or poor visualization may result from technique, patient positioning, or the amount of contrast used and should therefore be interpreted within the procedural context.',
    whatToLookFor: 'Look for ductal opacification, the course of the main and major biliary ducts, contrast passage, and any unexpected filling defect or interruption.',
    commonMistake: 'Focusing only on the presence of contrast without evaluating the entire ductal course or considering image quality and fluoroscopic exposure.',
    safetyQualityNote: 'Fluoroscopy should be performed according to the ALARA principle by minimizing exposure time, using appropriate collimation, avoiding unnecessary repeat images, maintaining appropriate distance, and using radiation protection for staff.',
    finalImpression: 'An educational case demonstrating the use of a C-Arm for intraoperative cholangiography, with emphasis on systematic assessment, image quality, and radiation safety.',
    takeaway: 'During intraoperative fluoroscopy, diagnostic or procedural image quality should be achieved with the lowest reasonable radiation exposure, and every image should provide a clear clinical or procedural benefit.',
    status: 'PUBLISHED',
    seo: {
      title: 'Intraoperative Cholangiography Using C-Arm | Hidden Radiology',
      description: 'An educational case on C-Arm intraoperative cholangiography with emphasis on image quality and radiation safety.',
      canonical: '/en/cases/c-arm-intraoperative-cholangiogram',
    },
  },
  {
    id: 'c-arm-lumbar-pedicle-screw',
    language: 'en',
    slug: 'c-arm-lumbar-pedicle-screw',
    title: 'Lumbar Pedicle Screw Guidance Using C-Arm',
    modality: 'C-Arm',
    region: 'Lumbar Spine',
    clinicalContext: 'An educational case demonstrating the use of a C-Arm during spinal surgery to guide the placement of fixation screws within the lumbar vertebrae.',
    indication: 'Assistance in identifying spinal levels and guiding and reviewing the position of fixation screws during spinal surgery.',
    technique: 'Use of a C-Arm to obtain appropriate fluoroscopic images during the procedure, using suitable views to identify the vertebral level and assess hardware position.',
    image: '/cases/c-arm/to_lumbar_pedicle_screw_fluoro.jpg',
    imageDescription: 'Educational fluoroscopic image demonstrating the use of a C-Arm to guide placement of a fixation screw in the lumbar spine.',
    supportingImage: '/cases/illustrations/safety/c_arm_arm_ls.jpg',
    supportingImageDescription: 'Educational image highlighting quality and safety considerations during C-Arm use in spinal surgery, with emphasis on reducing exposure time and improving imaging efficiency.',
    keyFindings: 'Assess vertebral level identification, alignment, hardware trajectory and position relative to the bony structures, and whether the views obtained are appropriate for the procedure.',
    interpretation: 'Fluoroscopic images should be assessed systematically in relation to the anatomy, projection used, and stage of the surgical procedure.',
    differentialDiagnosis: 'Apparent malalignment or difficulty identifying hardware position may result from positioning, image quality, or projection angle. Technique should therefore be reviewed before concluding that a true problem is present.',
    whatToLookFor: 'Review the vertebral level, alignment, screw position and trajectory, relationship to the bony structures, any apparent breach or unexpected position, and the quality of the selected projection.',
    commonMistake: 'Relying on a single image or projection to judge screw position without considering the appropriate views and the stage of the surgical procedure.',
    safetyQualityNote: 'Fluoroscopic guidance requires balancing the need for imaging with radiation dose reduction. Appropriate collimation, minimized fluoroscopy time, avoidance of unnecessary repeat exposure, adequate distance, and protective barriers for staff should be used.',
    finalImpression: 'An educational case demonstrating C-Arm guidance and review of lumbar fixation with emphasis on imaging accuracy, image quality, and radiation safety.',
    takeaway: 'In spinal surgery, a useful image is one that answers the procedural question with the lowest reasonable radiation exposure, rather than simply obtaining more images.',
    status: 'PUBLISHED',
    seo: {
      title: 'Lumbar Pedicle Screw Guidance Using C-Arm | Hidden Radiology',
      description: 'An educational case on C-Arm guidance for lumbar pedicle screw placement with emphasis on quality and radiation safety.',
      canonical: '/en/cases/c-arm-lumbar-pedicle-screw',
    },
  },
  {
    id: 'c-arm-distal-radius-orif',
    language: 'en',
    slug: 'c-arm-distal-radius-orif',
    title: 'Distal Radius Fracture Fixation Using C-Arm',
    modality: 'C-Arm',
    region: 'Wrist and Distal Radius',
    clinicalContext: 'An educational case demonstrating the use of a C-Arm during surgical fixation of a distal radius fracture to assess alignment and hardware position.',
    indication: 'Guidance and review of surgical fixation of a distal radius fracture, including assessment of alignment and hardware position during the procedure.',
    technique: 'Use of a C-Arm to obtain fluoroscopic images during surgical fixation, with appropriate projections selected to assess alignment, bone structures, and fixation hardware.',
    image: '/cases/c-arm/distal_radius_orif_ap_fluoroscopic_teaching_case.jpg',
    imageDescription: 'Educational fluoroscopic image demonstrating surgical fixation of a distal radius fracture at the wrist using a C-Arm.',
    supportingImage: '/cases/illustrations/safety/c_arm_wrest.jpg',
    supportingImageDescription: 'Educational image highlighting quality and safety principles during C-Arm use in upper-limb surgery, with emphasis on minimizing radiation exposure while obtaining adequate procedural images.',
    keyFindings: 'Assess bony alignment, hardware position and its relationship to the bone and joint, any obvious malalignment, and the quality of the images obtained during the procedure.',
    interpretation: 'Fluoroscopic images are used to review the stages of fixation sequentially and confirm that the procedural objective is being achieved, while considering the projection and positioning for each image.',
    differentialDiagnosis: 'Apparent differences in alignment or hardware position may result from variations in projection angle or limb positioning and should therefore be interpreted using appropriate views.',
    whatToLookFor: 'Assess alignment, hardware position, relationship to the articular surface and bony structures, any apparent breach or undesirable position, and image quality.',
    commonMistake: 'Judging the success of fixation from a single image without reviewing appropriate projections or considering changes in projection angle.',
    safetyQualityNote: 'Required procedural images should be obtained with the lowest reasonable radiation exposure. Fluoroscopy time should be minimized, appropriate collimation used, unnecessary repeat images avoided, and suitable radiation protection applied.',
    finalImpression: 'An educational case demonstrating C-Arm use during distal radius fracture fixation, with emphasis on alignment, hardware position, image quality, and radiation safety.',
    takeaway: 'Effective fluoroscopy in orthopedic surgery means obtaining the images necessary for procedural decisions while minimizing unnecessary radiation exposure.',
    status: 'PUBLISHED',
    seo: {
      title: 'Distal Radius Fracture Fixation Using C-Arm | Hidden Radiology',
      description: 'An educational case on C-Arm use during distal radius fracture fixation with emphasis on image quality and radiation safety.',
      canonical: '/en/cases/c-arm-distal-radius-orif',
    },
  },
  {
    id: 'cath-lab-lad-critical-stenosis',
    language: 'en',
    slug: 'cath-lab-lad-critical-stenosis',
    title: 'Critical 90% Stenosis of the LAD',
    modality: 'Cath Lab',
    region: 'Coronary Arteries',
    clinicalContext: 'A 58-year-old patient with persistent chest pain and an abnormal ECG was urgently referred to the cardiac catheterization laboratory for coronary evaluation.',
    indication: 'Evaluation of the coronary arteries in a patient with persistent symptoms and abnormal ECG findings, with suspected significant coronary stenosis.',
    technique: 'Coronary angiography using a Judkins Left catheter positioned at the left coronary ostium, with an appropriate LAO caudal projection for assessment of the coronary arteries.',
    image: '/cases/cath%20lab%20coronary%20cases/image_1.jpg',
    imageDescription: 'Coronary fluoroscopic angiogram demonstrating severe stenosis of the mid left anterior descending artery (LAD).',
    supportingImage: '/cases/illustrations/safety/cardiac_cath_lab.jpg',
    supportingImageDescription: 'Educational image related to quality and safety in cardiac catheterization, emphasizing radiation dose optimization while obtaining the required diagnostic images.',
    keyFindings: 'There is severe, approximately 90% stenosis in the mid LAD, with marked luminal narrowing compared with the adjacent reference segment.',
    interpretation: 'The image demonstrates severe coronary stenosis in the mid LAD. The severity should be interpreted in the clinical context and with review of the available coronary projections rather than from a single image alone.',
    differentialDiagnosis: 'The apparent severity of stenosis may be affected by projection angle, vessel overlap, and image quality. Appropriate additional projections should be reviewed before final assessment.',
    whatToLookFor: 'Assess the location, severity, and extent of the stenosis, compare the vessel lumen with an appropriate reference segment, and look for vessel overlap or technical factors that may affect interpretation.',
    commonMistake: 'Estimating stenosis severity from a single projection without considering projection angle, vessel overlap, or comparison with an appropriate reference segment.',
    safetyQualityNote: 'Coronary fluoroscopy should follow the ALARA principle, with minimized exposure time, appropriate collimation, avoidance of unnecessary images, and appropriate radiation protection for staff.',
    finalImpression: 'Educational coronary angiographic case demonstrating severe mid-LAD stenosis, with emphasis on systematic assessment, image quality, and radiation safety.',
    takeaway: 'In coronary angiography, identifying a stenosis is only the first step. Its location, extent, and severity should be assessed systematically using appropriate projections and adequate image quality before procedural decisions are made.',
    status: 'PUBLISHED',
    seo: {
      title: 'Critical 90% LAD Stenosis | Hidden Radiology',
      description: 'Educational coronary angiography case demonstrating severe mid-LAD stenosis with emphasis on systematic interpretation, image quality, and radiation safety.',
      canonical: '/en/cases/cath-lab-lad-critical-stenosis',
    },
  },

  {
    id: 'cath-lab-rca-pci-stent',
    language: 'en',
    slug: 'cath-lab-rca-pci-stent',
    title: 'RCA Coronary Stent Placement — Before and After',
    modality: 'Cath Lab',
    region: 'Right Coronary Artery',
    clinicalContext: 'A 62-year-old patient with an inferior myocardial infarction was found to have critical stenosis of the right coronary artery (RCA) on coronary angiography.',
    indication: 'Evaluation and treatment of critical RCA stenosis using percutaneous coronary intervention (PCI) to restore coronary flow and improve luminal caliber.',
    technique: 'Right coronary angiography before and after intervention, followed by wire crossing, balloon angioplasty, stent deployment, and assessment of the final angiographic result and coronary flow.',
    image: '/cases/cath%20lab%20coronary%20cases/realistic_fluoroscopy_rca_stent_2.jpg',
    imageDescription: 'Educational fluoroscopic image demonstrating the right coronary artery before and after stent placement.',
    supportingImage: '/cases/illustrations/safety/coronary_angiography_stent_rca.jpg',
    supportingImageDescription: 'Educational image related to quality and safety during PCI and coronary stent placement, emphasizing radiation optimization and acquisition of only the images required for the procedure.',
    keyFindings: 'Before intervention, there is severe narrowing involving the proximal to mid RCA with reduced distal flow. After intervention, there is marked improvement in luminal caliber and restoration of coronary flow.',
    interpretation: 'The before-and-after comparison demonstrates a clear improvement in luminal appearance and coronary flow following treatment. The final result should be assessed for residual stenosis, stent position and expansion, and distal coronary flow.',
    differentialDiagnosis: 'Residual narrowing should be distinguished from apparent narrowing caused by projection angle or vessel overlap. Appropriate post-intervention projections should be reviewed.',
    whatToLookFor: 'Compare the vessel lumen before and after intervention, assess stent position and expansion, look for residual stenosis, and evaluate distal coronary flow.',
    commonMistake: 'Judging PCI success from luminal enlargement alone without assessing coronary flow, stent position, stent expansion, and residual stenosis in appropriate projections.',
    safetyQualityNote: 'PCI requires balancing repeated imaging needs with radiation dose reduction. Appropriate collimation, minimized fluoroscopy time, avoidance of unnecessary repeat acquisitions, and suitable radiation protection should be maintained.',
    finalImpression: 'Educational case demonstrating improvement of the right coronary artery following PCI and stent placement, with emphasis on before-and-after assessment, procedural result, image quality, and radiation safety.',
    takeaway: 'Successful coronary intervention should not be judged by luminal enlargement alone. The final assessment should systematically include stent position, residual stenosis, and coronary flow.',
    status: 'PUBLISHED',
    seo: {
      title: 'RCA Coronary Stent Placement | Hidden Radiology',
      description: 'Educational PCI case demonstrating right coronary artery stent placement with before-and-after angiographic assessment.',
      canonical: '/en/cases/cath-lab-rca-pci-stent',
    },
  },

  {
    id: 'cath-lab-rca-cto-collaterals',
    language: 'en',
    slug: 'cath-lab-rca-cto-collaterals',
    title: 'Chronic Total Occlusion of the RCA with Collateral Circulation',
    modality: 'Cath Lab',
    region: 'Right Coronary Artery and Collateral Circulation',
    clinicalContext: 'A 68-year-old patient with chronic angina and a clinical history consistent with chronic total occlusion of the right coronary artery (RCA).',
    indication: 'Assessment of a chronic total coronary occlusion and evaluation of the collateral circulation supplying the territory beyond the occlusion.',
    technique: 'Coronary angiography using appropriate projections to assess the total occlusion and collateral circulation, with attention to collateral pathways arising from the contralateral coronary circulation.',
    image: '/cases/cath%20lab%20coronary%20cases/image_3.jpg',
    imageDescription: 'Educational coronary angiographic image demonstrating chronic total occlusion of the RCA with collateral circulation.',
    supportingImage: '/cases/illustrations/safety/cath_lab_cto_procedure.jpg',
    supportingImageDescription: 'Educational image related to quality and safety during CTO intervention, emphasizing procedural planning, radiation dose optimization, and acquisition of only necessary images.',
    keyFindings: 'There is complete occlusion of the proximal RCA with a defined occlusion end, while collateral vessels provide blood flow to the distal portion of the artery.',
    interpretation: 'The case demonstrates a chronic total coronary occlusion with collateral circulation, an important feature when assessing coronary anatomy and planning intervention. The collateral pathways and their connection to the distal vessel should be evaluated carefully.',
    differentialDiagnosis: 'A true chronic total occlusion should be distinguished from acute occlusion or apparent occlusion caused by vessel overlap or inadequate imaging. The angiographic appearance should be correlated with the clinical history and additional projections.',
    whatToLookFor: 'Assess the beginning and morphology of the occlusion, the distal RCA, and the collateral pathways supplying the territory beyond the occlusion.',
    commonMistake: 'Focusing only on the occlusion site while overlooking the distal vessel and collateral circulation, which are essential for understanding the complete coronary anatomy.',
    safetyQualityNote: 'CTO procedures may require careful planning because of their potential length and complexity. Radiation exposure should be minimized using appropriate collimation, avoidance of unnecessary imaging, and appropriate monitoring of cumulative dose and exposure.',
    finalImpression: 'Chronic total occlusion of the RCA with collateral circulation in an educational case focused on collateral anatomy, procedural planning, image quality, and radiation safety.',
    takeaway: 'In CTO cases, understanding the collateral circulation and distal vessel is as important as identifying the occlusion itself. A complete understanding of the coronary anatomy is fundamental to procedural planning.',
    status: 'PUBLISHED',
    seo: {
      title: 'RCA Chronic Total Occlusion with Collateral Circulation | Hidden Radiology',
      description: 'Educational CTO case demonstrating chronic total occlusion of the right coronary artery with collateral circulation and emphasis on anatomy, planning, and radiation safety.',
      canonical: '/en/cases/cath-lab-rca-cto-collaterals',
    },
  },
  {
    id: 'ultrasound-gallbladder-cholelithiasis',
    language: 'en',
    slug: 'ultrasound-gallbladder-cholelithiasis',
    title: 'Cholelithiasis with Chronic Cholecystitis',
    modality: 'Ultrasound',
    region: 'Gallbladder',
    clinicalContext: 'Educational case demonstrating gallstones and gallbladder wall thickening on ultrasound.',
    indication: 'Assessment of suspected gallbladder disease and characterization of gallstones.',
    technique: 'Ultrasound examination of the gallbladder using standard abdominal scanning planes and Doppler assessment when appropriate.',
    image: '/cases/us/gallbladder_cholelithiasis_ultrasound.jpg',
    imageDescription: 'Ultrasound image demonstrating multiple gallstones with posterior acoustic shadowing and gallbladder wall thickening.',
    supportingImage: '/cases/illustrations/safety/us_gallbladder_ultrasound_infographic.jpg',
    supportingImageDescription: 'Educational ultrasound quality and safety illustration emphasizing patient identification, probe disinfection, thermal index monitoring, and documentation.',
    keyFindings: 'The gallbladder is enlarged with a wall thickness of 4.7 mm. Multiple hyperechoic gallstones demonstrate posterior acoustic shadowing. The findings should be correlated with the clinical context.',
    interpretation: 'The sonographic appearance is compatible with cholelithiasis with gallbladder wall changes that require correlation with the clinical presentation.',
    differentialDiagnosis: 'Consider acute cholecystitis, chronic gallbladder disease, sludge, and other causes of gallbladder wall thickening according to the clinical context.',
    whatToLookFor: 'Assess gallbladder size, wall thickness, number and mobility of stones, posterior acoustic shadowing, pericholecystic findings, and sonographic tenderness when appropriate.',
    commonMistake: 'Identifying gallstones without systematically assessing the gallbladder wall and surrounding structures.',
    safetyQualityNote: 'Apply ALARA principles, minimize unnecessary scanning time and acoustic output, disinfect the probe after every patient, use appropriate probe-cover and infection-control procedures, and maintain patient privacy and comfort.',
    finalImpression: 'Cholelithiasis with gallbladder wall thickening in an educational ultrasound case focused on systematic assessment, image quality, and patient safety.',
    takeaway: 'Gallstones should be assessed together with gallbladder wall appearance and the clinical context rather than interpreted in isolation.',
    status: 'PUBLISHED',
    seo: {
      title: 'Cholelithiasis with Chronic Cholecystitis on Ultrasound | Hidden Radiology',
      description: 'Educational ultrasound case demonstrating gallstones and gallbladder wall thickening with emphasis on systematic assessment, quality, and safety.',
      canonical: '/en/cases/ultrasound-gallbladder-cholelithiasis',
    },
  },
  {
    id: 'ultrasound-thyroid-tirads-4',
    language: 'en',
    slug: 'ultrasound-thyroid-tirads-4',
    title: 'Thyroid Nodule Moderately Suspicious',
    modality: 'Ultrasound',
    region: 'Right Thyroid Lobe',
    clinicalContext: 'Educational case demonstrating a moderately suspicious thyroid nodule requiring structured sonographic assessment.',
    indication: 'Characterization of a thyroid nodule and assessment of suspicious sonographic features.',
    technique: 'High-frequency thyroid ultrasound with transverse and longitudinal views, measurements, Doppler assessment, and systematic evaluation of cervical structures.',
    image: '/cases/us/thyroid_ultrasound_tirads4.jpg',
    imageDescription: 'Ultrasound image demonstrating a hypoechoic right thyroid lobe nodule with suspicious sonographic features.',
    supportingImage: '/cases/illustrations/safety/us_image_2.jpg',
    supportingImageDescription: 'Educational thyroid ultrasound quality and safety illustration emphasizing ALARA, patient communication, ergonomics, and infection control.',
    keyFindings: 'A 1.12 cm hypoechoic nodule is identified in the right thyroid lobe with irregular margins, microcalcifications, and internal Doppler flow.',
    interpretation: 'The sonographic features are suspicious and correspond to a TIRADS 4 pattern. Further management, including consideration of FNA, should follow the applicable risk-stratification criteria and clinical context.',
    differentialDiagnosis: 'Differential considerations include benign thyroid nodules, follicular-pattern lesions, and malignant thyroid neoplasms. Final assessment requires correlation with the complete sonographic criteria and clinical findings.',
    whatToLookFor: 'Assess composition, echogenicity, shape, margins, calcifications, vascularity, size, and cervical lymph nodes using a structured thyroid ultrasound approach.',
    commonMistake: 'Focusing on nodule size alone while overlooking margins, calcifications, composition, and other risk-stratification features.',
    safetyQualityNote: 'Apply ALARA principles, minimize unnecessary acoustic exposure, communicate the examination clearly to the patient, maintain proper probe-handling ergonomics, and follow infection-control procedures.',
    finalImpression: 'Moderately suspicious right thyroid lobe nodule, TIRADS 4, in an educational ultrasound case emphasizing structured characterization and patient safety.',
    takeaway: 'Thyroid nodules should be risk-stratified using a structured assessment of their sonographic features rather than size alone.',
    status: 'PUBLISHED',
    seo: {
      title: 'TIRADS 4 Thyroid Nodule on Ultrasound | Hidden Radiology',
      description: 'Educational ultrasound case demonstrating a moderately suspicious right thyroid nodule with emphasis on structured assessment and safety.',
      canonical: '/en/cases/ultrasound-thyroid-tirads-4',
    },
  },
  {
    id: 'ultrasound-ovarian-simple-cyst',
    language: 'en',
    slug: 'ultrasound-ovarian-simple-cyst',
    title: 'Ovarian Simple Cyst',
    modality: 'Ultrasound',
    region: 'Ovary',
    clinicalContext: 'Educational case demonstrating a simple anechoic ovarian cyst and systematic cyst characterization.',
    indication: 'Evaluation and characterization of an ovarian cystic lesion.',
    technique: 'Pelvic ultrasound with systematic assessment of the ovaries in appropriate imaging planes and Doppler evaluation of the lesion when indicated.',
    image: '/cases/us/image_4.jpg',
    imageDescription: 'Educational ultrasound image demonstrating a simple anechoic ovarian cyst.',
    supportingImage: '/cases/illustrations/safety/image_3.jpg',
    supportingImageDescription: 'Educational ultrasound safety illustration emphasizing ALARA, infection control, patient privacy, comfort, and examiner ergonomics.',
    keyFindings: 'A simple anechoic ovarian cyst is demonstrated without described solid internal components.',
    interpretation: 'The sonographic appearance is compatible with a simple ovarian cyst. Interpretation should be based on the patient’s age, clinical context, and cyst size.',
    differentialDiagnosis: 'A simple cyst should be distinguished from complex cystic lesions by assessing the wall, internal contents, septations, solid components, and vascularity.',
    whatToLookFor: 'Assess cyst size, internal echogenicity, wall thickness, septations, solid components, and Doppler vascularity.',
    commonMistake: 'Describing any cystic lesion as simple without systematically evaluating its wall, contents, and internal components.',
    safetyQualityNote: 'Apply ALARA principles and minimize unnecessary acoustic exposure while maintaining appropriate image quality. Clean the probe, follow infection-control procedures, and preserve patient privacy and comfort.',
    finalImpression: 'Simple anechoic ovarian cyst in an educational case focused on systematic cyst characterization and ultrasound quality and safety.',
    takeaway: 'Ovarian cyst characterization depends on the internal appearance, wall, associated components, and clinical context—not simply the presence of fluid.',
    status: 'PUBLISHED',
    seo: {
      title: 'Simple Ovarian Cyst on Ultrasound | Hidden Radiology',
      description: 'Educational case demonstrating a simple ovarian cyst with emphasis on systematic ultrasound characterization, quality, and safety.',
      canonical: '/en/cases/ultrasound-ovarian-simple-cyst',
    },
  },]











