import { Product } from '../../lib/types'

export const enProducts: Product[] = [
  {
    id: 'cxr-vol1',
    sku: 'HR-CXR-EN-001',
    language: 'en',
    slug: 'ana-fahim-cxr-en',
    title: 'Ana Fahim | Chest X-Ray - Vol. 1',
    subtitle: 'Vol. 1',
    description: 'The definitive clinical guide for mastering chest radiography: positioning precision, systematic 7-step interpretation, and practical diagnostic pearls.',
    category: 'X-Ray',
    modality: 'Chest X-Ray',
    cover: '/assets/images/en/cxr-cover.jpg',
    screenshots: ['/images/products/en/cxr-01.jpg', '/images/products/en/cxr-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/chest-xray',
    status: 'PUBLISHED',
    seo: {
      title: 'Ana Fahim | Chest X-Ray - Vol. 1 | Hidden Radiology',
      description: 'The definitive clinical guide for mastering chest radiography - positioning precision and systematic interpretation',
      canonical: '/en/products/ana-fahim-cxr-en',
      ogImage: '/assets/images/en/cxr-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
  {
    id: 'ct-vol2',
    sku: 'HR-CT-EN-001',
    language: 'en',
    slug: 'ana-fahim-ct-en',
    title: 'Ana Fahim | CT Mastery - Vol. 2',
    subtitle: 'Vol. 2',
    description: 'Mastering HU scale, windowing parameters, dose optimization, and artifact reduction in clinical computed tomography.',
    category: 'CT',
    modality: 'Computed Tomography',
    cover: '/assets/images/en/ct-cover.jpg',
    screenshots: ['/images/products/en/ct-01.jpg', '/images/products/en/ct-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/IUNDERSTANDCTScan',
    status: 'PUBLISHED',
    seo: {
      title: 'Ana Fahim | CT Mastery - Vol. 2 | Hidden Radiology',
      description: 'Mastering HU scale, windowing parameters, dose optimization, and artifact reduction in clinical CT',
      canonical: '/en/products/ana-fahim-ct-en',
      ogImage: '/assets/images/en/ct-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
  {
    id: 'mri-vol3',
    sku: 'HR-MRI-EN-001',
    language: 'en',
    slug: 'ana-fahim-mri-en',
    title: 'Ana Fahim | MRI Mastery - Vol. 3',
    subtitle: 'Vol. 3',
    description: '50 essential hidden signs, pulse sequence fundamentals, and clinical safety protocols in magnetic resonance imaging.',
    category: 'MRI',
    modality: 'Magnetic Resonance Imaging',
    cover: '/assets/images/en/mri-cover.jpg',
    screenshots: ['/images/products/en/mri-01.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/hidden-radiology-mri-international',
    status: 'PUBLISHED',
    seo: {
      title: 'Ana Fahim | MRI Mastery - Vol. 3 | Hidden Radiology',
      description: '50 essential hidden signs, pulse sequence fundamentals, and clinical safety protocols in MRI',
      canonical: '/en/products/ana-fahim-mri-en',
      ogImage: '/assets/images/en/mri-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
  {
    id: 'qs-vol4',
    sku: 'HR-QS-EN-001',
    language: 'en',
    slug: 'radiology-quality-safety-en',
    title: 'Ana Fahim | Quality & Safety - Vol. 4',
    subtitle: 'Vol. 4',
    description: 'Comprehensive guidelines on departmental quality management, patient safety protocols, and international standards.',
    category: 'Quality & Safety',
    modality: 'General',
    cover: '/assets/images/en/qs-cover.jpg',
    screenshots: [],
    price: 7.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/radiology-quality-safety-en-final',
    status: 'PUBLISHED',
    seo: {
      title: 'Ana Fahim | Quality & Safety - Vol. 4 | Hidden Radiology',
      description: 'Comprehensive guidelines on departmental quality management, patient safety protocols, and international standards',
      canonical: '/en/products/radiology-quality-safety-en',
      ogImage: '/assets/images/en/qs-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
  {
    id: 'rs-vol5',
    sku: 'HR-RS-EN-001',
    language: 'en',
    slug: 'ana-fahim-radiation-safety-en',
    title: 'Ana Fahim | Radiation Safety - Vol. 5',
    subtitle: 'Vol. 5',
    description: 'Advanced radiation protection, ALARA principles, dose monitoring, and regulatory compliance for medical imaging facilities.',
    category: 'Radiation Safety',
    modality: 'General',
    cover: '/assets/images/en/rs-cover.jpg',
    screenshots: [],
    price: 7.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-radiation-safety',
    status: 'PUBLISHED',
    seo: {
      title: 'Ana Fahim | Radiation Safety - Vol. 5 | Hidden Radiology',
      description: 'Advanced radiation protection, ALARA principles, dose monitoring, and regulatory compliance for medical imaging',
      canonical: '/en/products/ana-fahim-radiation-safety-en',
      ogImage: '/assets/images/en/rs-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
]
