import { Product } from '../../lib/types'

export const enProducts: Product[] = [
  {
    id: 'hr-cxr-en-001',
    sku: 'HR-CXR-EN-001',
    language: 'en',
    slug: 'ana-fahim-cxr-en',
    title: 'I Understand | Chest X-Ray Mastery',
    subtitle: 'Complete Edition v2.0',
    description: 'A comprehensive guide for radiographers covering chest X-ray imaging techniques, film interpretation, and common error detection. Includes real clinical cases and insights from 30 years of professional experience.',
    category: 'X-Ray',
    modality: 'Chest X-Ray',
    cover: '/images/products/en/cxr-cover.jpg',
    screenshots: ['/images/products/en/cxr-01.jpg', '/images/products/en/cxr-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-cxr-en',
    status: 'PUBLISHED',
    seo: {
      title: 'I Understand | Chest X-Ray Mastery Guide — Radiography Training | Hidden Radiology',
      description: 'Comprehensive chest X-ray guide for radiographers - imaging techniques, film interpretation, and clinical case studies',
      canonical: '/en/products/ana-fahim-cxr-en',
      ogImage: '/images/products/en/cxr-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
  {
    id: 'hr-ct-en-001',
    sku: 'HR-CT-EN-001',
    language: 'en',
    slug: 'ana-fahim-ct-en',
    title: 'I Understand | Computed Tomography (CT)',
    subtitle: 'Your Simplified Guide Before Entering the CT Room',
    description: 'A practical and comprehensive guide explaining CT from fundamentals to mastery. Includes protocols, imaging techniques, and safety guidelines for new and experienced radiographers.',
    category: 'CT',
    modality: 'Computed Tomography',
    cover: '/images/products/en/ct-cover.jpg',
    screenshots: ['/images/products/en/ct-01.jpg', '/images/products/en/ct-02.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-ct-en',
    status: 'PUBLISHED',
    seo: {
      title: 'I Understand | CT Scan Guide — Computed Tomography Training | Hidden Radiology',
      description: 'Practical CT guide from basics to advanced - protocols, techniques, and safety guidelines for radiographers',
      canonical: '/en/products/ana-fahim-ct-en',
      ogImage: '/images/products/en/ct-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
  {
    id: 'hr-mri-en-001',
    sku: 'HR-MRI-EN-001',
    language: 'en',
    slug: 'ana-fahim-mri-en',
    title: 'I Understand | Magnetic Resonance Imaging (MRI)',
    subtitle: 'Everything You Need to Know About MRI',
    description: 'A comprehensive guide covering MRI sequences, contrast agents, safety protocols, and image interpretation. Practical resource for radiographers and physicians.',
    category: 'MRI',
    modality: 'Magnetic Resonance Imaging',
    cover: '/images/products/en/mri-cover.jpg',
    screenshots: ['/images/products/en/mri-01.jpg'],
    price: 4.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-mri-en',
    status: 'PUBLISHED',
    seo: {
      title: 'I Understand | MRI Guide — Magnetic Resonance Imaging Training | Hidden Radiology',
      description: 'Comprehensive MRI guide covering sequences, contrast, safety, and image interpretation for radiographers',
      canonical: '/en/products/ana-fahim-mri-en',
      ogImage: '/images/products/en/mri-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
  {
    id: 'hr-qs-en-001',
    sku: 'HR-QS-EN-001',
    language: 'en',
    slug: 'radiology-quality-safety-en',
    title: 'I Understand | Radiology Quality & Safety',
    subtitle: 'Professional Standards Guide',
    description: 'Quality assurance and radiation safety standards in radiology departments. Essential resource for radiologic technologists, department managers, and quality assurance personnel. Includes checklists, assessment templates, and compliance guidelines.',
    category: 'Quality & Safety',
    modality: 'General',
    cover: '/images/products/en/qs-cover.jpg',
    screenshots: [],
    price: 7.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/radiology-quality-safety-en',
    status: 'PUBLISHED',
    seo: {
      title: 'I Understand | Radiology Quality & Safety Guide — QA Standards | Hidden Radiology',
      description: 'Quality assurance and radiation safety standards for radiology departments - checklists and compliance guidelines',
      canonical: '/en/products/radiology-quality-safety-en',
      ogImage: '/images/products/en/qs-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
  {
    id: 'hr-rs-en-001',
    sku: 'HR-RS-EN-001',
    language: 'en',
    slug: 'ana-fahim-radiation-safety-en',
    title: 'I Understand | Radiation Safety',
    subtitle: 'Radiation Protection Principles',
    description: 'Fundamentals of radiation protection, ALARA principles, patient and occupational dose management, and international regulatory compliance. Essential for all radiology professionals.',
    category: 'Radiation Safety',
    modality: 'General',
    cover: '/images/products/en/rs-cover.jpg',
    screenshots: [],
    price: 7.99,
    currency: 'USD',
    gumroadUrl: 'https://radioviewer.gumroad.com/l/ana-fahim-radiation-safety-en',
    status: 'PUBLISHED',
    seo: {
      title: 'I Understand | Radiation Safety Guide — ALARA Principles | Hidden Radiology',
      description: 'Radiation protection fundamentals, ALARA principles, dose management, and regulatory compliance for radiology professionals',
      canonical: '/en/products/ana-fahim-radiation-safety-en',
      ogImage: '/images/products/en/rs-cover.jpg',
    },
    disclaimer: 'This is a digital product. Instant download. No physical shipping.',
  },
]
